### ISSUE TITLE
Question:  What is app.css#ux for?

### ISSUE THREAD

**Issue by wshayes** [aurelia/app-ux-showcase#24]
Not a bug!  Just a question.

In the app.html file, there is a require statement with something I don't understand.

      <require from="./app.css#ux"></require>

What is the #ux for?  In regular URI's it's used as an internal target, but I don't see anything like that in the app.css file.

**Comment by ZHollingshead** [comment]
This marks the CSS file to be processed by Aurelia UX, allowing javascript style interpolation to be used to insert variables into the file. Here is a snippet from that file showing this.

``` css
styles.header {
  background: ${$design.primary};
  color: ${$design.primaryForeground};
  box-shadow: 0 2px 5px rgba(0, 0, 0, 0.26);
  padding: 16px;
  font-size: 24px;
  line-height: 32px;
  height: 64px;
}
```
